### ISSUE TITLE
Transition artifact from bintray to maven central

### ISSUE THREAD

**Issue by charles-wp** [omarsmak/kafka-consumer-lag-monitoring#29]
It's apparent that JFrog are sunsetting the Bintray repository that's being used to host this package.  They recommend uploading to Maven Central.  See https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ for details.

Can the build process of the artifact be pushed over to Maven Central?

**Comment by omarsmak** [comment]
Thanks for the heads up! I wasn't aware of it. I will do the migration soon and I hope it won't be complicated

**Comment by charles-wp** [comment]
Could you give an update on the progress on transitioning to Maven Central?  We have an internal project that may fail to build in the coming weeks, without pointing it at another source.

**Comment by omarsmak** [comment]
I didn't have enough time to go through the complete migration. However the namespace `com.omarsmak` has been created in sonatype, thus is about making sure the release fits this [requirements](https://central.sonatype.org/publish/requirements/) and the gradle build modifications as specified [here](https://central.sonatype.org/publish/publish-gradle/). Therefore, a help here would be appreciated to prepare the project in terms requirements and gradle build modifications, I can take over later when it comes to signing the artifacts since it will need my credentials

**Comment by charles-wp** [comment]
Thanks for the update, I'll see what I can do from my project.

**Comment by omarsmak** [comment]
Hey @charles-wp , I have now moved the build to Maven Central. Builds have been published in sonatype and I have notified sonatype support team to sync it with maven central, it maybe take few days I guess

**Comment by omarsmak** [comment]
Sync has been completed https://repo1.maven.org/maven2/com/omarsmak/kafka/consumer-lag-monitoring/0.1.1/

**Comment by charles-wp** [comment]
That's great news.  I was able to carve out some time to assist for the coming week, but it looks like you got there first.  Many thanks for getting it sorted.
